### ISSUE TITLE
Feature Request - Skip certain postman paths

### ISSUE THREAD

**Issue by thim81** [loadimpact/postman-to-k6#77]
Hi,

In postman, we typically have a range of CRUD operations (including DELETE).

Our aim is to use the K6 script in a continuous integration Azure pipeline, where after each push to GIT > we convert our OpenApi spec (with examples) to a postman collection > which we convert to a K6 script (using the excellent postman-to-k6) > which we then trigger to execute "K6 run" to run a loadtest

I'm looking for a manner to skip certain POSTMAN operations/paths (like DELETE)
Do you have any pointers?

An alternative could be that, I use the `--separate `option  (like `postman-to-k6 collection.json --separate -o k6-script.js` )and then define in my Azure pipeline which files to execute.

```
steps:
  - task: k6-load-test@0
    inputs:
      filename: 'k6-script_1.js'

  - task: k6-load-test@0
    inputs:
      filename: 'k6-script_2.js'
```

Or is there another way to be able to skip certain postman paths from being executed by the K6 run?
